version: '3.7'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: photo_app
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - '5001:5000'

volumes:
  db:
